"""Trade models

Revision ID: dcb7f063b1b6
Revises: e5f3d99c49c3
Create Date: 2025-07-17 20:19:21.547106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcb7f063b1b6'
down_revision: Union[str, Sequence[str], None] = 'e5f3d99c49c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actives',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('market', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('operation_type', sa.Enum('BUY', 'SELL', name='order'), nullable=False),
    sa.Column('operation_date', sa.String(), nullable=False),
    sa.Column('input_price', sa.Float(), nullable=False),
    sa.Column('out_price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('profit_loss', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('ABERTA', 'FECHADA', name='statustrade'), nullable=False),
    sa.Column('active_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['active_id'], ['actives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operations')
    op.drop_table('actives')
    # ### end Alembic commands ###
